apiVersion: v1
kind: Service
metadata:
  name: clothing-classifier
spec:
  type: NodePort
  selector:
    app: clothing-classifier
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
